fix(dot): install when list is empty
LazyVim/LazyVim pull request #3052
Opened 2024-04-24 23:07 UTC by matadaniel

Assign `opts.ensure_installed` first because if it were to be nil, I believe that it would not be assigned nor extended with shellcheck.

Remove shfmt since LazyVim sets it up by default.

2024-04-25 10:23 UTC, rubiin requested changes
shfmt is removed , might wanna add it back

2024-04-25 10:36 UTC, dpetka2001 commented
`shfmt` is already installed [here by default](https://github.com/LazyVim/LazyVim/blob/f086bcde253c29be9a2b9c90b413a516f5d5a3b2/lua/lazyvim/plugins/lsp/init.lua#L238).

2024-04-25 10:37 UTC, rubiin commented
Oh cool will approve the pr then

2024-04-25 10:38 UTC, rubiin approved these changes

2024-04-25 14:17 UTC, rubiin commented
@amaanq Thanks for the headsup. By approval, it means it  passes checks . Since folke is a single collaborator with write access, without other people reviewing prs it would become cumbersome for him to manage all these prs.

2024-05-03 07:05 UTC, folke commented
I do agree with @amaanq RE the approvals.
Your intentions and enthusiasm are good, but it's indeed pretty annoying to get all those additional notifications :)

2024-05-03 07:06 UTC, merged

2024-05-03 07:06 UTC, folke commented
Thanks!